In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

In [4]:
train = pd.read_csv('train_processed.csv')
test = pd.read_csv('test_processed.csv')

In [5]:
train

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,...,Cabin_Deck_G,Cabin_Deck_T,Cabin_Side_P,Cabin_Side_S,Age_Group_0-5,Age_Group_13-18,Age_Group_19-35,Age_Group_36-55,Age_Group_55+,Age_Group_6-12
0,0001_01,0,39.0,0,0.0,0.0,0.0,0.0,0.0,False,...,0,0,1,0,0,0,0,1,0,0
1,0002_01,0,24.0,0,109.0,9.0,25.0,549.0,44.0,True,...,0,0,0,1,0,0,1,0,0,0
2,0003_01,0,58.0,1,43.0,3576.0,0.0,6715.0,49.0,False,...,0,0,0,1,0,0,0,0,1,0
3,0003_02,0,33.0,0,0.0,1283.0,371.0,3329.0,193.0,False,...,0,0,0,1,0,0,1,0,0,0
4,0004_01,0,16.0,0,303.0,70.0,151.0,565.0,2.0,True,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,False,...,0,0,1,0,0,0,0,1,0,0
8689,9278_01,1,18.0,0,0.0,0.0,0.0,0.0,0.0,False,...,1,0,0,1,0,1,0,0,0,0
8690,9279_01,0,26.0,0,0.0,0.0,1872.0,1.0,0.0,True,...,1,0,0,1,0,0,1,0,0,0
8691,9280_01,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,False,...,0,0,0,1,0,0,1,0,0,0
8692,9280_02,0,44.0,0,126.0,4688.0,0.0,0.0,12.0,True,...,0,0,0,1,0,0,0,1,0,0

In [6]:
test

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Cabin_Num,...,Cabin_Deck_G,Cabin_Deck_T,Cabin_Side_P,Cabin_Side_S,Age_Group_0-5,Age_Group_13-18,Age_Group_19-35,Age_Group_36-55,Age_Group_55+,Age_Group_6-12
0,0013_01,1,27.0,0,0.0,0.0,0.0,0.0,0.0,3,...,1,0,0,1,0,0,1,0,0,0
1,0018_01,0,19.0,0,0.0,9.0,0.0,2823.0,0.0,4,...,0,0,0,1,0,0,1,0,0,0
2,0019_01,1,31.0,0,0.0,0.0,0.0,0.0,0.0,0,...,0,0,0,1,0,0,1,0,0,0
3,0021_01,0,38.0,0,0.0,6652.0,0.0,181.0,585.0,1,...,0,0,0,1,0,0,0,1,0,0
4,0023_01,0,20.0,0,10.0,0.0,635.0,0.0,0.0,5,...,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,1,34.0,0,0.0,0.0,0.0,0.0,0.0,1496,...,1,0,0,1,0,0,1,0,0,0
4273,9269_01,0,42.0,0,0.0,847.0,17.0,10.0,144.0,427,...,0,0,0,1,0,0,0,1,0,0
4274,9271_01,1,27.0,0,0.0,0.0,0.0,0.0,0.0,296,...,0,0,1,0,0,0,1,0,0,0
4275,9273_01,0,27.0,0,0.0,2680.0,0.0,0.0,523.0,297,...,0,0,1,0,0,0,1,0,0,0
4276,9277_01,1,43.0,0,0.0,0.0,0.0,0.0,0.0,1498,...,1,0,0,1,0,0,0,1,0,0

In [ ]:
model = RandomForestClassifier()